name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@main
      with:
        submodules: recursive
    - name: install dependencies
      run: "sudo apt install libcriterion-dev libxcb-xkb-dev libxcb-util-dev libasound2-dev"
    - name: test
      run: "make check"
