name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@main
      with:
        submodules: recursive
    - name: testing library
      run: "sudo apt-get install libcriterion-dev"
    - name: test
      run: "make check"
